// src/app/contact/page.tsx
"use client";

import { useState } from 'react';
import {
  MapPin,
  Mail,
  Phone,
  Send,
  MessageSquare,
  Clock,
  ChevronDown,
  ChevronUp
} from 'lucide-react';

export default function ContactPage() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [expandedFaq, setExpandedFaq] = useState<number | null>(null);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);

    // Simulate form submission
    setTimeout(() => {
      setSubmitting(false);
      setSubmitted(true);
      setName('');
      setEmail('');
      setSubject('');
      setMessage('');

      // Reset success message after 5 seconds
      setTimeout(() => {
        setSubmitted(false);
      }, 5000);
    }, 1500);
  };

  const toggleFaq = (index: number) => {
    setExpandedFaq(expandedFaq === index ? null : index);
  };

  const faqs = [
    {
      question: "How can I get started with MimesisAI?",
      answer: "Getting started is easy! Simply create an account, explore our image generation tools, and start creating. Our free tier allows you to generate a limited number of images per month to try out the service."
    },
    {
      question: "What payment methods do you accept?",
      answer: "We accept all major credit cards (Visa, Mastercard, American Express), as well as PayPal. For enterprise customers, we also offer invoicing options."
    },
    {
      question: "Can I use the images generated by MimesisAI commercially?",
      answer: "Yes, all images generated using MimesisAI are yours to use, including for commercial purposes. Please refer to our Terms of Service for complete details on usage rights."
    },
    {
      question: "How do I report a technical issue?",
      answer: "For technical issues, please use the contact form on this page and select 'Technical Support' as the subject. Our team aims to respond within 24 hours on business days."
    },
    {
      question: "Do you offer API access?",
      answer: "Yes, we offer API access on our Professional and Enterprise plans. Visit our API Access page for detailed documentation and integration guides."
    }
  ];

  return (
    <div className="container mx-auto px-4 py-16">
      <div className="max-w-5xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-bold mb-6 text-center bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
          Contact Us
        </h1>
        <p className="text-center text-gray-300 mb-12 max-w-2xl mx-auto">
          Have questions about MimesisAI or need assistance? Our team is here to help.
          Reach out to us using the form below or through our direct contact methods.
        </p>

        <div className="grid md:grid-cols-3 gap-12">
          {/* Contact Form */}
          <div className="md:col-span-2 bg-black/20 rounded-xl p-6 border border-white/5">
            <h2 className="text-2xl font-semibold mb-6 text-white flex items-center">
              <MessageSquare className="w-5 h-5 mr-2 text-purple-400" />
              Send Us a Message
            </h2>

            {submitted ? (
              <div className="bg-green-500/20 border border-green-500/30 rounded-lg p-4 text-green-400 mb-4">
                Thank you for your message! We'll get back to you shortly.
              </div>
            ) : null}

            <form onSubmit={handleSubmit}>
              <div className="grid sm:grid-cols-2 gap-4 mb-4">
                <div>
                  <label htmlFor="name" className="block text-sm font-medium text-gray-400 mb-1">
                    Your Name
                  </label>
                  <input
                    type="text"
                    id="name"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    className="w-full px-4 py-2 bg-black/30 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500/50"
                    required
                  />
                </div>
                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-gray-400 mb-1">
                    Email Address
                  </label>
                  <input
                    type="email"
                    id="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="w-full px-4 py-2 bg-black/30 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500/50"
                    required
                  />
                </div>
              </div>

              <div className="mb-4">
                <label htmlFor="subject" className="block text-sm font-medium text-gray-400 mb-1">
                  Subject
                </label>
                <select
                  id="subject"
                  value={subject}
                  onChange={(e) => setSubject(e.target.value)}
                  className="w-full px-4 py-2 bg-black/30 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500/50"
                  required
                >
                  <option value="">Select a subject</option>
                  <option value="General Inquiry">General Inquiry</option>
                  <option value="Technical Support">Technical Support</option>
                  <option value="Billing Question">Billing Question</option>
                  <option value="Feature Request">Feature Request</option>
                  <option value="Partnership">Partnership</option>
                </select>
              </div>

              <div className="mb-6">
                <label htmlFor="message" className="block text-sm font-medium text-gray-400 mb-1">
                  Your Message
                </label>
                <textarea
                  id="message"
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  rows={6}
                  className="w-full px-4 py-2 bg-black/30 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500/50"
                  required
                ></textarea>
              </div>

              <button
                type="submit"
                disabled={submitting}
                className={`px-6 py-3 rounded-lg flex items-center justify-center gap-2 w-full ${submitting
                    ? 'bg-purple-500/50 cursor-not-allowed'
                    : 'bg-gradient-to-r from-purple-600 to-blue-600 hover:opacity-90'
                  } text-white font-medium transition-all`}
              >
                {submitting ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                    Sending...
                  </>
                ) : (
                  <>
                    <Send className="w-4 h-4" />
                    Send Message
                  </>
                )}
              </button>
            </form>
          </div>

          {/* Contact Info */}
          <div className="space-y-6">
            <div className="bg-black/20 rounded-xl p-6 border border-white/5">
              <h2 className="text-xl font-semibold mb-6 text-white">Contact Information</h2>

              <div className="space-y-4">
                <div className="flex items-start">
                  <div className="mt-1 bg-purple-500/20 p-2 rounded-full mr-4">
                    <Mail className="w-5 h-5 text-purple-400" />
                  </div>
                  <div>
                    <h3 className="text-sm font-medium text-gray-400">Email</h3>
                    <a href="mailto:support@mimesisai.com" className="text-white hover:text-purple-400 transition-colors">
                      support@mimesisai.com
                    </a>
                  </div>
                </div>

                <div className="flex items-start">
                  <div className="mt-1 bg-purple-500/20 p-2 rounded-full mr-4">
                    <Phone className="w-5 h-5 text-purple-400" />
                  </div>
                  <div>
                    <h3 className="text-sm font-medium text-gray-400">Phone</h3>
                    <a href="tel:+1-555-123-4567" className="text-white hover:text-purple-400 transition-colors">
                      +1 (555) 123-4567
                    </a>
                  </div>
                </div>

                <div className="flex items-start">
                  <div className="mt-1 bg-purple-500/20 p-2 rounded-full mr-4">
                    <MapPin className="w-5 h-5 text-purple-400" />
                  </div>
                  <div>
                    <h3 className="text-sm font-medium text-gray-400">Address</h3>
                    <p className="text-white">
                      123 AI Innovation Center<br />
                      San Francisco, CA 94103<br />
                      United States
                    </p>
                  </div>
                </div>

                <div className="flex items-start">
                  <div className="mt-1 bg-purple-500/20 p-2 rounded-full mr-4">
                    <Clock className="w-5 h-5 text-purple-400" />
                  </div>
                  <div>
                    <h3 className="text-sm font-medium text-gray-400">Business Hours</h3>
                    <p className="text-white">
                      Monday - Friday: 9AM - 6PM PST<br />
                      Weekend: Closed
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-br from-purple-900/30 to-blue-900/30 rounded-xl p-6 border border-purple-500/10">
              <h3 className="text-xl font-medium mb-2 text-white">Need Enterprise Support?</h3>
              <p className="text-gray-300 mb-4">
                Contact our enterprise team for custom solutions and dedicated support.
              </p>
              <a
                href="mailto:enterprise@mimesisai.com"
                className="inline-block px-4 py-2 bg-white/10 rounded-lg text-white hover:bg-white/20 transition-colors"
              >
                Contact Enterprise Team
              </a>
            </div>
          </div>
        </div>

        {/* FAQ Section */}
        <div className="mt-16">
          <h2 className="text-2xl md:text-3xl font-semibold mb-8 text-white text-center">
            Frequently Asked Questions
          </h2>
          <div className="max-w-3xl mx-auto space-y-4">
            {faqs.map((faq, index) => (
              <div
                key={index}
                className="bg-black/20 border border-white/10 rounded-lg overflow-hidden"
              >
                <button
                  className="w-full p-4 flex justify-between items-center text-left"
                  onClick={() => toggleFaq(index)}
                >
                  <span className="text-white font-medium">{faq.question}</span>
                  {expandedFaq === index ? (
                    <ChevronUp className="w-5 h-5 text-purple-400" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-purple-400" />
                  )}
                </button>
                {expandedFaq === index && (
                  <div className="p-4 pt-0 text-gray-300 border-t border-white/10">
                    {faq.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
